### ISSUE TITLE
Intacct SDK throws exception - "Control block is missing senderid element" response while performing operation in Intacct 

### ISSUE THREAD

**Issue by skmuruganjbfcs** [intacct/intacct-sdk-net#215]
Hi,
We are getting the below exception while performing operations in intacct.

Exception:
Read function control ID: a0c6b58a-0e90-4091-be0f-b84e2ff6b440
Number of GLENTRY objects read on run 2249: 1000
Intacct.Sdk.Exceptions.IntacctException: Control block is missing senderid element
   at Intacct.Sdk.Xml.Response.Control..ctor(XElement control)
   at Intacct.Sdk.Xml.AbstractResponse..ctor(Stream body)
   at Intacct.Sdk.Xml.SynchronousResponse..ctor(Stream body)
   at Intacct.Sdk.Xml.RequestHandler.<ExecuteSynchronous>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Intacct.Sdk.AbstractClient.
[IntacctLog.txt](https://github.com/intacct/intacct-sdk-net/files/9453801/IntacctLog.txt)
<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Intacct.Sdk.IntacctClient.<Execute>d__4.MoveNext()

**Comment by laurelkhall** [comment]
Are you using Execute or Executebatch?

According to the  (https://developer.intacct.com/tools/sdk-net/#error-handling ):

An IntacctException extends the System.Exception and is **_likely an issue with Sage Intacct itself._**

The **Execute** and **ExecuteBatch** functions have some built-in error handling for the results ([Result](https://intacct.github.io/intacct-sdk-net/class_intacct_1_1_s_d_k_1_1_xml_1_1_response_1_1_result.html) instances) coming back:

- **Execute** allows you to execute one function to the Sage Intacct API. This will also grab the Result and call EnsureStatusSuccess to check for any API errors executing the single API function.
- **ExecuteBatch** allows you to execute multiple functions to the Sage Intacct API in the same request.
 If the passed RequestConfig.Transaction property evaluates to true, it will loop through each Result and call EnsureStatusNotFailure in an attempt to check for any API errors that are status failed and not aborted.
 If the passed RequestConfig.Transaction property evaluates to false (default), you will need to do your own Result looping and error checking.

**Comment by dylan-holt-sage** [comment]
@skmuruganjbfcs, has this issue been resolved? If so, please let me know so I can close this issue. Thanks.

**Comment by laurelkhall** [comment]
No, it is not resolved. We had no reply from SI yet. Is there anyone who can take a look?
