### ISSUE TITLE
API Suddenly Stopped Working

### ISSUE THREAD

**Issue by smunk-varis** [intacct/intacct-sdk-net#256]
The following sample is from a Unit Test I am using to work out Sage Intacct communications. This WAS working, then suddenly stopped. Please also see the exception following the code sample:
````
    private ClientConfig IntacctConfig
    {
      get
      {
        return new ClientConfig()
        {
          SenderId = "MySenderID",
          SenderPassword = "MySenderPassword",
          CompanyId = "MyCompanyId",
          UserId = "MyUserId",
          UserPassword = "MyUserPassword",
          SessionId = $"{Guid.NewGuid()}",
          EndpointUrl = "https://api.intacct.com/ia/xml/xmlgw.phtml"
        };
      }
    }

    [TestMethod]
    public void Validation_Test()
    {
      bool isSuccess = false;
      string assertionMsg = string.Empty;

      try
      {
        Task<ClientConfig> validateTask = SessionProvider.Factory(IntacctConfig);
        validateTask.Wait();
        ClientConfig sessionConfig = validateTask.Result;

        OnlineClient sageClient = new OnlineClient(sessionConfig);

        RequestConfig requestConfig = new RequestConfig()
        {
          ControlId = assertionMsg
        };

        Intacct.SDK.Functions.Common.ReadByQuery vendorQuery = new Intacct.SDK.Functions.Common.ReadByQuery()
        {
          ObjectName = "VENDOR"
          , PageSize = 1000
          //, Query = ((Intacct.SDK.Functions.Common)new Intacct.SDK.Functions.Common.NewQuery())
          //,Fields =
          //{
          //  "RECORDNO",
          //  "VENDORID",
          //  "NAME"
          //}
        };

        Task<Intacct.SDK.Xml.OnlineResponse> clientTask = sageClient.Execute(vendorQuery, requestConfig);
        clientTask.Wait();
        Intacct.SDK.Xml.OnlineResponse taskResponse = clientTask.Result;

        //taskResponse.

        isSuccess = true;


      }
      catch (Exception ex)
      {
        assertionMsg = ex.Message;
        isSuccess = false;
      }

      Assert.IsTrue(isSuccess, assertionMsg);
    }
````

Exception:
````
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Varis.WinService.Workflow.Tests.WorkflowIntacctTests.Validation_Test() in C:\Users\....\Varis.WinService.Workflow.Tests\WorkflowIntacctTests.cs:line 85

  This exception was originally thrown at this call stack:
    Intacct.SDK.Xml.AbstractResponse.AbstractResponse(System.IO.Stream)
    Intacct.SDK.Xml.OnlineResponse.OnlineResponse(System.IO.Stream)
    Intacct.SDK.Xml.RequestHandler.ExecuteOnline(System.Collections.Generic.List<Intacct.SDK.Functions.IFunction>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Intacct.SDK.AbstractClient.ExecuteOnlineRequest(System.Collections.Generic.List<Intacct.SDK.Functions.IFunction>, Intacct.SDK.RequestConfig)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Intacct.SDK.OnlineClient.Execute(Intacct.SDK.Functions.IFunction, Intacct.SDK.RequestConfig)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]

Inner Exception 1:
ResponseException: Response control status failure - GW-0021 Invalid session [Request ID: 8e8ae7969c8717dc-SJC]
````

**Comment by smunk-varis** [comment]
D'OH!!!!

I removed the SessionId from my ClientConfig definition and my code was functional again. Whoops!
